# Generated by Django 6.0.2 on 2026-03-01 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_queue_and_sla'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWorkflowModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Outpatient', 'Outpatient'), ('Inpatient', 'Inpatient'), ('Emergency', 'Emergency'), ('Follow-up', 'Follow-up')], help_text='Request category', max_length=20, unique=True)),
                ('modifier_type', models.CharField(choices=[('add_front', 'Add to Front'), ('add_after', 'Add After'), ('skip', 'Skip Departments'), ('replace', 'Replace Workflow')], default='add_front', help_text='Type of modification to apply', max_length=20)),
                ('departments_to_add', models.JSONField(blank=True, default=list, help_text='Departments to add (for add_front, add_after)')),
                ('departments_to_skip', models.JSONField(blank=True, default=list, help_text='Departments to skip (for skip modifier)')),
                ('apply_to_request_types', models.JSONField(blank=True, default=list, help_text='Which request types this modifier applies to (empty = all)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this modifier is active')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority modifiers are applied first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Workflow Modifier',
                'verbose_name_plural': 'Category Workflow Modifiers',
                'ordering': ['-priority', 'category'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('MRI', 'MRI'), ('X-Ray', 'X-Ray'), ('CT Scan', 'CT Scan'), ('Ultrasound', 'Ultrasound'), ('Cardiac', 'Cardiac'), ('ECG', 'ECG'), ('Blood Test', 'Blood Test'), ('Surgery', 'Surgery'), ('General Checkup', 'General Checkup'), ('Dental', 'Dental'), ('Eye', 'Eye'), ('Optical', 'Optical'), ('Physiotherapy', 'Physiotherapy'), ('Vaccination', 'Vaccination')], help_text='Request type this workflow applies to', max_length=50, unique=True)),
                ('workflow_steps', models.JSONField(default=list, help_text="List of departments in order (e.g., ['Reception', 'Radiology', 'Billing'])")),
                ('initial_department', models.CharField(help_text='Initial department for this request type', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workflow is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow Definition',
                'verbose_name_plural': 'Workflow Definitions',
                'ordering': ['request_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-priority', 'queue_position', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='requesthistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Request histories'},
        ),
        migrations.AlterField(
            model_name='department',
            name='current_load',
            field=models.IntegerField(default=0, help_text='Current number of active requests', validators=[django.core.validators.MinValueValidator(0, message='Load cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Department description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether department is active'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Department name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='threshold',
            field=models.IntegerField(default=5, help_text='Maximum capacity before overload', validators=[django.core.validators.MinValueValidator(1, message='Threshold must be at least 1'), django.core.validators.MaxValueValidator(100, message='Threshold cannot exceed 100')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_department',
            field=models.ForeignKey(blank=True, help_text='Department handling this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='core.department'),
        ),
        migrations.AlterField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AlterField(
            model_name='request',
            name='patient_name',
            field=models.CharField(help_text='Patient full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency')], default='Normal', help_text='Request priority level', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(help_text='Type of medical service requested', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Assigned', help_text='Current request status', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department at time of this history entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_history', to='core.department'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this history entry'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='request',
            field=models.ForeignKey(help_text='The request this history belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.request'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='status',
            field=models.CharField(help_text='Status at this point in history', max_length=100),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='core_depart_name_80d4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='core_depart_is_acti_ae42f9_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='core_reques_status_27d5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['priority'], name='core_reques_priorit_f03f30_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['request_type'], name='core_reques_request_1cab04_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['created_at'], name='core_reques_created_ee7b30_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['patient_name'], name='core_reques_patient_82369c_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['category'], name='core_reques_categor_ba1faa_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['queue_position'], name='core_reques_queue_p_428db8_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['is_escalated'], name='core_reques_is_esca_18ee93_idx'),
        ),
        migrations.AddIndex(
            model_name='requesthistory',
            index=models.Index(fields=['request', '-timestamp'], name='core_reques_request_249644_idx'),
        ),
    ]
